const keys = new Map();
// keys.set(0, 'c1');
// keys.set(1, 'cs1');
// keys.set(2, 'd1');
// keys.set(3, 'eb1');
// keys.set(4, 'e1');
// keys.set(5, 'f1');
// keys.set(6, 'fs1');
// keys.set(7, 'g1');
// keys.set(8, 'gs1');
// keys.set(9, 'a1');
// keys.set(10, 'bb1');
// keys.set(11, 'b1');
// keys.set(12, 'c');
// keys.set(13, 'cs');
// keys.set(14, 'd');
// keys.set(15, 'eb');
// keys.set(16, 'e');
// keys.set(17, 'f');
// keys.set(18, 'fs');
// keys.set(19, 'g');
// keys.set(20, 'gs');
// keys.set(21, 'a');
// keys.set(22, 'bb');
// keys.set(23, 'b');
keys.set("KeyQ", 'c1');
keys.set("Digit2", 'cs1');
keys.set("KeyW", 'd1');
keys.set("Digit3", 'eb1');
keys.set("KeyE", 'e1');
keys.set("KeyR", 'f1');
keys.set("Digit4", 'fs1');
keys.set("KeyT", 'g1');
keys.set("Digit6", 'gs1');
keys.set("KeyY", 'a1');
keys.set("Digit7", 'bb1');
keys.set("KeyU", 'b1');
keys.set("KeyZ", 'c');
keys.set("KeyS", 'cs');
keys.set("KeyX", 'd');
keys.set("KeyD", 'eb');
keys.set("KeyC", 'e');
keys.set("KeyV", 'f');
keys.set("KeyF", 'fs');
keys.set("KeyB", 'g');
keys.set("KeyH", 'gs');
keys.set("KeyN", 'a');
keys.set("KeyJ", 'bb');
keys.set("KeyM", 'b');

export default keys;